function [beamformed_Image_out,delay] = pcicuda_batch_caller(RF_Arr, element_Pos_Array_um_X, speed_Of_Sound_umps, RF_Start_Time, sampling_Freq, image_Range_X_um, image_Range_Z_um, p_epsilon, n_elements)

    % Start timing
    % fprintf('Starting combcuda function call...\n');
    tic;
% size(element_Pos_Array_um_X) % should be [2, 128]
    % Call the CUDA function
beamformed_Image_out = comcudas_RCB_20( ...
    single(RF_Arr), ...
    single(element_Pos_Array_um_X), ...
    single(speed_Of_Sound_umps), ...
    single(RF_Start_Time), ...
    single(sampling_Freq), ...
    single(image_Range_X_um), ...
    single(image_Range_Z_um), ...
    single(p_epsilon), ...
    single(n_elements) ...
);
% beamformed_Image_out = combcudav( ...
%     RF_Arr, ...
%     element_Pos_Array_um_X, ...
%     speed_Of_Sound_umps, ...
%     RF_Start_Time, ...
%     sampling_Freq, ...
%     image_Range_X_um, ...
%     image_Range_Z_um, ...
%     p_epsilon, ...
%     n_elements ...
% );

    % End timing
    delay = toc;
    
    % fprintf('combcuda function call completed in %.4f seconds.\n', elapsedTime);

end
